name: Data Engineering events notifier

on:
  schedule:
    #- cron: "0 12 * * 7"
    - cron: 10 * * * *

jobs:
  update_raw_snowflake_table:
    name: Update raw snowflake table
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Environment setup
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          DATABASE_ID:  ${{secrets.DATABASE_ID}}
          BEARER_TOKEN: ${{secrets.BEARER_TOKEN}}
          USER:         ${{secrets.USER}}
          PASSWORD:     ${{secrets.PASSWORD}}
          ACCOUNT:      ${{secrets.ACCOUNT}}
          WAREHOUSE:    ${{secrets.WAREHOUSE}}
          DATABASE:     ${{secrets.DATABASE}}
          SCHEMA:       ${{secrets.SCHEMA}}
        run: |
          python main.py